Repository anchovycation/metronom, pull requests merged in 2022-07, with the labels that each got.

#32 Utilites.safeWrite's business logic fixed
  lib/Model.ts
  lib/ModelInstance.ts
  lib/utility.ts
Labels: bug

#35 `ModelInstance.destroy()` function added
  example/basic.js
  lib/ModelInstance.ts
Labels: ready for review

#38 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, ready for review

#37 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, ready for review

#39 Create CHANGELOG.md
  CHANGELOG.md
Labels: documentation, ready for review

#46 proxy added
  lib/ModelInstance.ts
Labels: ready for review
